### ISSUE TITLE
is:issue is:open Question? -> Why dont you use talib for technical indicator?

### ISSUE THREAD

**Issue by Mr-Nobody-dey** [pythonlessons/FinRock#2]
Nice Work. I also want to endeavor in this area. Currently I am in learning phase.

**Comment by pythonlessons** [comment]
Hey, thanks!

I am not using talib for indicators because I still would need a wrapper for it. Because if we want to include indicators in training, I need to know some details about it, such as minimum, maximum and etc. Usually, this step may require custom preprocessing. Also, I use custom render scheme that I also need to use adapt if I want it to work. So it's way easier for me just to reimplement these indicators than using external library. But, if you don't want to use render, or you know how to preprocess each indicator properly, you can use talib indicators :)

**Comment by Mr-Nobody-dey** [comment]
Ok. Thanks man. I hope you build a perfect trading model which excels in real trading. Do share the model though :).

**Comment by pythonlessons** [comment]
There is no perfect model, but I will be happy if I make profits with real data :)
